Update SCA.yml

diff --git a/.github/workflows/SCA.yml b/.github/workflows/SCA.yml
--- a/.github/workflows/SCA.yml
+++ b/.github/workflows/SCA.yml
@@ -15,10 +15,10 @@ jobs:
         with:
           fetch-depth: 0 
 
-      - name: SonarQube Source Code Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+     # - name: SonarQube Source Code Scan
+      #  uses: SonarSource/sonarcloud-github-action@master
+     #   env:
+       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
       #- name: SonarQube Quality Gate check
        # id: sonarqube-quality-gate-check
@@ -45,17 +45,17 @@ jobs:
           snyk test --all-projects --json > snyk_report.json || true
         shell: bash
 
-      - name: Debug Snyk JSON Output
-        run: |
-          echo "Printing snyk_report.json:"
-          cat snyk_report.json
-          echo "Formatted output using jq:"
-          jq '.' snyk_report.json
-        shell: bash
+     # - name: Debug Snyk JSON Output
+      #  run: |
+     #     echo "Printing snyk_report.json:"
+        #  cat snyk_report.json
+       #   echo "Formatted output using jq:"
+        #  jq '.' snyk_report.json
+       # shell: bash
 
-      - name: Monitor Snyk SCA Scan
-        run: snyk monitor --all-projects
-        continue-on-error: true
+    #  - name: Monitor Snyk SCA Scan
+    #    run: snyk monitor --all-projects
+    #    continue-on-error: true
 
      # - name: Check for Medium or Higher Severity Issues
       #  id: snyk-check
@@ -69,28 +69,62 @@ jobs:
       #    fi
       #  shell: bash
 
-      - name: Check for Medium, High, and Critical Severity Issues
-        id: snyk-check
+      #- name: Check for Medium, High, and Critical Severity Issues
+       # id: snyk-check
+      #  run: |
+       #   medium_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium")] | length' snyk_report.json)
+        #  high_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "high")] | length' snyk_report.json)
+        #  critical_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "critical")] | length' snyk_report.json)
+
+       #  echo "Medium issues: $medium_issues"
+        #  echo "High issues: $high_issues"
+         # echo "Critical issues: $critical_issues"
+
+         # if [ "$critical_issues" -gt 0 ]; then
+          #  echo "Job failed: Found $critical_issues critical severity issues."
+          #  exit 1
+         # else
+        #    echo "No critical severity issues found."
+         #   echo "Medium issues: $medium_issues"
+         #   echo "High issues: $high_issues"
+          #  echo "Job passed despite $((medium_issues + high_issues)) medium and high severity issues."
+        #  fi
+       # shell: bash
+
+      - name: ZAP Dynamic Analysis Scan
+        uses: zaproxy/action-full-scan@v0.12.0
+        with:
+          target: 'https://bwapp.hakhub.net/'
+          rules_file_name: '.github/workflows/rules.zap'
+          format: 'json'  # Output the result in JSON format
+          report_file_name: 'zap_report.json'  # Save the report to a file
+
+      - name: Debug ZAP JSON Output
         run: |
-          medium_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium")] | length' snyk_report.json)
-          high_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "high")] | length' snyk_report.json)
-          critical_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "critical")] | length' snyk_report.json)
+          echo "ZAP JSON Report:"
+          cat zap_report.json
+          echo "Formatted ZAP JSON Output:"
+          jq '.' zap_report.json
+        shell: bash
+
+
+      - name: Check ZAP Scan Issues
+        id: zap-check
+        run: |
+          medium_issues=$(jq '[.site[].alerts[] | select(.risk == "Medium")] | length' zap_report.json)
+          high_issues=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' zap_report.json)
 
           echo "Medium issues: $medium_issues"
           echo "High issues: $high_issues"
-          echo "Critical issues: $critical_issues"
 
-          if [ "$critical_issues" -gt 0 ]; then
-            echo "Job failed: Found $critical_issues critical severity issues."
+          total_issues=$((medium_issues + high_issues))
+          if [ "$total_issues" -gt 0 ]; then
+            echo "Job failed: Found $total_issues medium and high severity issues."
             exit 1
           else
-            echo "No critical severity issues found."
-            echo "Medium issues: $medium_issues"
-            echo "High issues: $high_issues"
-            echo "Job passed despite $((medium_issues + high_issues)) medium and high severity issues."
+            echo "No medium or high severity issues found. Job passed."
           fi
         shell: bash
-
 
 
       #- name: ZAP Dynamic Analysis Scan
