Update SCA.yml

diff --git a/.github/workflows/SCA.yml b/.github/workflows/SCA.yml
--- a/.github/workflows/SCA.yml
+++ b/.github/workflows/SCA.yml
@@ -15,17 +15,17 @@ jobs:
         with:
           fetch-depth: 0 
 
-      - name: SonarQube Source Code Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+     # - name: SonarQube Source Code Scan
+      #  uses: SonarSource/sonarcloud-github-action@master
+      #  env:
+      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: Generate SonarQube JSON Report
-        run: |
-          curl -u ${{ secrets.SONAR_TOKEN }}: \
-            "https://sonarcloud.io/api/measures/component_tree?component=vivek28058_Skillviz_BE&metricKeys=ncloc,complexity,violations,bugs,vulnerabilities,code_smells" \
-            -o sonar_report.json
-        shell: bash
+   #   - name: Generate SonarQube JSON Report
+    #    run: |
+     #     curl -u ${{ secrets.SONAR_TOKEN }}: \
+      #      "https://sonarcloud.io/api/measures/component_tree?component=vivek28058_Skillviz_BE&metricKeys=ncloc,complexity,violations,bugs,vulnerabilities,code_smells" \
+       #     -o sonar_report.json
+       # shell: bash
 
      # - name: SonarQube Quality Gate check
       #  id: sonarqube-quality-gate-check
@@ -34,65 +34,65 @@ jobs:
       #  env:
       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: Upload SonarQube Report
-        uses: actions/upload-artifact@v3
-        with:
-           name: sonar-report
-           path: sonar_report.json
+     # - name: Upload SonarQube Report
+      #  uses: actions/upload-artifact@v3
+       # with:
+       #    name: sonar-report
+        #   path: sonar_report.json
 
-      - name: Install Snyk
-        run: npm install -g snyk
+     # - name: Install Snyk
+      #  run: npm install -g snyk
 
-      - name: Authenticate Snyk
-        run: snyk auth ${{ secrets.SNYK_TOKEN }}
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+    #  - name: Authenticate Snyk
+     #   run: snyk auth ${{ secrets.SNYK_TOKEN }}
+      #  env:
+       #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
-      - name: Run Snyk Dependencies Scan
-        id: snyk-scan
-        run: |
-          snyk test --all-projects --json > snyk_report.json || true
-        shell: bash
+     # - name: Run Snyk Dependencies Scan
+      #  id: snyk-scan
+      #  run: |
+      #    snyk test --all-projects --json > snyk_report.json || true
+       # shell: bash
 
-      - name: Debug Snyk JSON Output
-        run: |
-          echo "Printing snyk_report.json:"
-          cat snyk_report.json
-          echo "Formatted output using jq:"
-          jq '.' snyk_report.json
-        shell: bash
+     # - name: Debug Snyk JSON Output
+      #  run: |
+       #   echo "Printing snyk_report.json:"
+        #  cat snyk_report.json
+         # echo "Formatted output using jq:"
+        #  jq '.' snyk_report.json
+        #shell: bash
 
-      - name: Monitor Snyk SCA Scan
-        run: snyk monitor --all-projects
-        continue-on-error: true
+    #  - name: Monitor Snyk SCA Scan
+     #   run: snyk monitor --all-projects
+      #  continue-on-error: true
 
-      - name: Check for Medium, High, and Critical Severity Issues
-        id: snyk-check
-        run: |
-          medium_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium")] | length' snyk_report.json)
-          high_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "high")] | length' snyk_report.json)
-          critical_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "critical")] | length' snyk_report.json)
+     # - name: Check for Medium, High, and Critical Severity Issues
+      #  id: snyk-check
+       # run: |
+        #  medium_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium")] | length' snyk_report.json)
+         # high_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "high")] | length' snyk_report.json)
+         # critical_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "critical")] | length' snyk_report.json)
 
-          echo "Medium issues: $medium_issues"
-          echo "High issues: $high_issues"
-          echo "Critical issues: $critical_issues"
+        #  echo "Medium issues: $medium_issues"
+        #  echo "High issues: $high_issues"
+         # echo "Critical issues: $critical_issues"
 
-          if [ "$critical_issues" -gt 0 ]; then
-            echo "Job failed: Found $critical_issues critical severity issues."
-            exit 1
-          else
-            echo "No critical severity issues found."
-            echo "Medium issues: $medium_issues"
-            echo "High issues: $high_issues"
-            echo "Job passed despite $((medium_issues + high_issues)) medium and high severity issues."
-          fi
-        shell: bash
+         # if [ "$critical_issues" -gt 0 ]; then
+          #  echo "Job failed: Found $critical_issues critical severity issues."
+          #  exit 1
+         # else
+          #  echo "No critical severity issues found."
+          #  echo "Medium issues: $medium_issues"
+          #  echo "High issues: $high_issues"
+          #  echo "Job passed despite $((medium_issues + high_issues)) medium and high severity issues."
+         # fi
+       # shell: bash
 
-      - name: Upload Snyk Report
-        uses: actions/upload-artifact@v3
-        with:
-            name: snyk-report
-            path: snyk_report.json
+     # - name: Upload Snyk Report
+      #  uses: actions/upload-artifact@v3
+      #  with:
+       #     name: snyk-report
+        #    path: snyk_report.json
 
       #- name: ZAP Dynamic Analysis Scan
       #  uses: zaproxy/action-full-scan@v0.12.0
